networks:
  docker-network:
    driver: bridge

services:
  backend:
    container_name: memorice-api
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./backend/.env
        required: true
    environment:
      DB_HOST: db
      ENVIRONMENT: production
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}

    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - /app/node_modules
    networks:
      - docker-network

  db:
    container_name: memorice-db
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/memorice
    ports:
      - "${DB_PORT}:5432"
    expose:
      - 5432
    env_file:
      - path: ./backend/.env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - docker-network

  frontend:
    container_name: memorice-frontend
    build:
      context: ./frontend
    env_file:
      - path: ./frontend/.env
        required: true
    ports:
      - "5173:80"
      - "80:80"
    depends_on:
      - backend
    networks:
      - docker-network

volumes:
  db-data:
